# 博客配置
title: 你的博客标题
subtitle: 你的博客副标题
description: 你的博客描述
author: 你的名字
language: zh-CN
timezone: Asia/Shanghai

# 菜单设置
menu:
  主页: /
  归档: /archives/
  分类: /categories/
  标签: /tags/

# 侧边栏设置
sidebar:
  # 侧边栏头像
  avatar: https://picsum.photos/200/200
  # 侧边栏社交链接
  social:
    - icon: fab fa-github
      url: https://github.com/你的用户名

# 文章设置
post:
  # 文章摘要字数
  excerpt_length: 200
